version: '3'

services:
    db:
        image: shop-database:latest
        volumes:
         - db_data:/var/lib/postgresql/data
         - db_log:/var/log/postgresql
    
    cms-db:
        image: cms-database:latest
        volumes:
         - cms_db_data:/var/lib/postgresql/data
         - cms_db_log:/var/log/postgresql
        ports:
         - "5432:5432"
    
    user-service:
        depends_on:
         - db
        image: shop-user-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - DB_HOST=db
         - DB_PORT=5432
         - SERVER_PORT=9000
        volumes:
         - user_service_log:/log
        restart: always
        ports:
         - "9001:9000"
    
    product-service:
        depends_on:
         - db
        image: shop-product-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - DB_HOST=db
         - DB_PORT=5432
         - SERVER_PORT=9000
        volumes:
         - product_service_log:/log
        restart: always
        ports:
         - "9002:9000"
    
    order-service:
        depends_on:
         - db
        image: shop-order-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - DB_HOST=db
         - DB_PORT=5432
         - SERVER_PORT=9000
        volumes:
         - order_service_log:/log
        restart: always
        ports:
         - "9003:9000"
    
volumes:
    db_data:
    db_log:
    user_service_log:
    product_service_log:
    order_service_log:
    federation_service_log:
    cms_db_data:
    cms_db_log:
