version: '3'

services:
    db:
        image: shop-database:latest
        volumes:
         - db_data:/var/lib/postgresql/data
         - db_log:/var/log/postgresql
        ports:
         - "5432:5432"
    
    user-service:
        depends_on:
         - db
        image: shop-user-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - DB_HOST=db
         - DB_PORT=5432
         - SERVER_PORT=9000
        volumes:
         - user_service_log:/log
        restart: always
    
    product-service:
        depends_on:
         - db
        image: shop-product-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - DB_HOST=db
         - DB_PORT=5432
         - SERVER_PORT=9000
        volumes:
         - product_service_log:/log
        restart: always
    
    federation-service:
        depends_on:
         - user-service
         - product-service
        image: shop-federation-service:latest
        user: "node"
        working_dir: /app
        environment:
         - NODE_ENV=production
         - USER_SERVICE_HOST=user-service
         - USER_SERVICE_PORT=9000
         - PRODUCT_SERVICE_HOST=product-service
         - PRODUCT_SERVICE_PORT=9000
         - SERVER_PORT=9000
        volumes:
         - federation_service_log:/log
        restart: always
        ports:
          - "9000:9000"

volumes:
    db_data:
    db_log:
    user_service_log:
    product_service_log:
    federation_service_log:
